CREATE OR REPLACE FORCE VIEW MFR_DOM_FINDING_SEVERITY_V AS
SELECT "SHORT_NAME","LONG_NAME" FROM MFR_DOM_FINDING_SEVERITY;
grant select on MFR_DOM_FINDING_SEVERITY_V to USR_LOGGING;
grant select on MFR_DOM_FINDING_SEVERITY_V to USR_REPORTING;


