CREATE OR REPLACE FORCE VIEW MFR_SCOPE_FINDING_V AS
SELECT "SCOPE_SUPPORTS_READINESS","RUN_ID","SCOPE_NAME" FROM MFR_SCOPE_FINDING;
grant select on MFR_SCOPE_FINDING_V to USR_LOGGING;
grant select on MFR_SCOPE_FINDING_V to USR_REPORTING;


