CREATE OR REPLACE FORCE VIEW MFR_PROGRAM_V AS
SELECT "PROGRAM_NAME","SCOPE_NAME","DATA_MIGRATION_STAGE","PROGRAM_TYPE" FROM MFR_PROGRAM;
grant select, insert, update, delete on MFR_PROGRAM_V to USR_LOGGING;
grant select, insert, update, delete on MFR_PROGRAM_V to USR_REPORTING;


