CREATE OR REPLACE FORCE VIEW MFR_RECON_CLIENT_SUBJECT_V
(language_code, language_name, client_subject_code, client_subject_name)
AS
SELECT 
  SBJ.LANGUAGE_CD,
  LNG.LANGUAGE_NM,
  SBJ.CLIENT_SUBJECT_CD,
  SBJ.CLIENT_SUBJECT_NM
FROM MFC_CLIENT_SUBJECT_V SBJ
JOIN MFL_DOM_LANGUAGE_V LNG
	ON SBJ.LANGUAGE_CD = LNG.LANGUAGE_CD;

