CREATE OR REPLACE FORCE VIEW MFC_MR_RCN_RB_VISIBLE_V AS
SELECT 
  MIGR_RUN_ID 
FROM MFC_MR_RCN_RB_VISIBLE;
grant select on MFC_MR_RCN_RB_VISIBLE_V to OWN_LOGGING;
grant select, insert, delete on MFC_MR_RCN_RB_VISIBLE_V to OWN_RECON;
grant select, insert, delete on MFC_MR_RCN_RB_VISIBLE_V to USR_RECONCILIATION;


