CREATE OR REPLACE FORCE VIEW MFR_SUBJECT_MATTER_V AS
SELECT "SUB_MAT_NAME","SUB_MAT_TYPE" FROM MFR_SUBJECT_MATTER;
grant select on MFR_SUBJECT_MATTER_V to USR_LOGGING;
grant select on MFR_SUBJECT_MATTER_V to USR_REPORTING;


