CREATE OR REPLACE FORCE VIEW MFR_PROCESS_V AS
SELECT "PROCESS_ID","PROCESS_START_TIME","RUN_ID","PROGRAM_NAME" FROM MFR_PROCESS;
grant select on MFR_PROCESS_V to USR_LOGGING;
grant select on MFR_PROCESS_V to USR_REPORTING;


