CREATE OR REPLACE FORCE VIEW MFR_DOM_PROGRAM_TYPE_V AS
SELECT "SHORT_NAME","LONG_NAME" FROM MFR_DOM_PROGRAM_TYPE;
grant select on MFR_DOM_PROGRAM_TYPE_V to USR_LOGGING;
grant select on MFR_DOM_PROGRAM_TYPE_V to USR_REPORTING;


