CREATE OR REPLACE FORCE VIEW MFR_DOM_DATA_MIGR_STAGE_V AS
SELECT "SHORT_NAME","LONG_NAME" FROM MFR_DOM_DATA_MIGR_STAGE;
grant select on MFR_DOM_DATA_MIGR_STAGE_V to USR_LOGGING;
grant select on MFR_DOM_DATA_MIGR_STAGE_V to USR_REPORTING;


