CREATE OR REPLACE TRIGGER MFR_RECON_POS_TMN_FND_V_IOUT
INSTEAD OF UPDATE ON MFR_RECON_POS_TMN_FND_V
FOR EACH ROW 
  BEGIN  
    UPDATE MFC_POS_TMN_FND_V
       SET POS_FND_COMMENT = :new.POS_FND_COMMENT,
           POS_FND_SIGN_OFF_FG = :new.POS_FND_SIGN_OFF_FG,
           POS_FND_BUG_FIX_ITIL_NO = :new.POS_FND_BUG_FIX_ITIL_NO
     WHERE FND_ID = :old.FND_ID;   
  END;
/

