CREATE OR REPLACE FORCE VIEW MFR_SYSTEM_V13 AS
SELECT 
  SYSTEM_ID, 
  SYSTEM_ROLE, 
  SYSTEM_USE, 
  SYSTEM_EXEC_ENVIRON, 
  PROPERTY_DESCRIPTION, 
  IS_RETIRED,
  HOST_NAME, 
  PORT_NO, 
  DB_INSTANCE_NAME, 
  DB_SCHEMA_NAME, 
  LOGIN_USER_NAME, 
  SYSTEM_TYPE 
FROM MFL_SYSTEM_V13;

