CREATE OR REPLACE FORCE VIEW MFR_RUN_ON_SYSTEM_V22 AS
SELECT 
  SYS.SYSTEM_ROLE,
  ROS.MFL_SYSTEM_SYSTEM_ID,
  ROS.MFL_MIGR_RUN_RUN_ID,
  ROS.SYSTEM_BANK_DT
FROM MFL_RUN_ON_SYSTEM_V22 ROS
JOIN MFL_SYSTEM_V22 SYS
ON ROS.MFL_SYSTEM_SYSTEM_ID = SYS.SYSTEM_ID;

