CREATE OR REPLACE FORCE VIEW MFR_MIGR_RUN_V13 AS
SELECT 
  RUN_ID,
  UC4_RUN_ID,
  RUN_STATUS,
  RUN_START_TIME,
  RUN_END_TIME,
  JOB_NETWORK_BUILD_ID,
  BANK_LOCATION_CODE,
  FACTORY_NAME
FROM MFL_MIGR_RUN_V13;

