CREATE OR REPLACE FORCE VIEW MFC_RCN_SCP_V AS
SELECT 
  RCN_SCOPE_TYP,
  RCN_SCOPE_GROUP,
  RCN_SCOPE_NAME,
  RCN_SCOPE_DESCR,
  RCN_SCOPE_RB_VISIBLE_FG
FROM MFC_RCN_SCP;
grant select, update on MFC_RCN_SCP_V to OWN_RECON;
grant select on MFC_RCN_SCP_V to USR_LOGGING;
grant select, update on MFC_RCN_SCP_V to USR_RECONCILIATION;


