CREATE OR REPLACE TRIGGER MFC_LDG_ERR_VAL_V_IOIT
INSTEAD OF INSERT ON MFC_LDG_ERR_VAL_V
FOR EACH ROW 
  BEGIN  
    INSERT INTO MFC_LDG_ERR_VAL
    ( ACS_LDG_ACC_KEY, 
    	ERR_VAL_ABS_D2K, 
    	ERR_VAL_PCT_D2K, 
    	ERR_VAL_TYPE
    ) VALUES 
    ( :new.ACS_LDG_ACC_KEY, 
    	:new.ERR_VAL_ABS_D2K, 
    	:new.ERR_VAL_PCT_D2K, 
    	CASE 
    		WHEN :new.ERR_VAL_ABS_D2K IS NOT NULL AND :new.ERR_VAL_PCT_D2K IS NULL THEN 'MFCRVLABS'
    		WHEN :new.ERR_VAL_PCT_D2K IS NOT NULL AND :new.ERR_VAL_ABS_D2K IS NULL THEN 'MFCRVLPCT'
    		ELSE NULL -- causes constraint violation on insert 
      END 
    );
  END;
/

