CREATE OR REPLACE TRIGGER MFC_CLIENT_SAMPLE_V_IOIT
INSTEAD OF INSERT ON MFC_CLIENT_SAMPLE_V
FOR EACH ROW 
  BEGIN  
    INSERT INTO MFC_CLIENT_SAMPLE
    ( SMPL_ID,
      BANK_LOCATION_CODE,
      CLIENT_ID,
      CLIENT_SUBJECT_CD,
      CLIENT_COMMENT
    ) VALUES 
    ( MFC_CLIENT_SAMPLE_SMPL_ID_SEQ.NEXTVAL, 
      :new.BANK_LOCATION_CODE,
      :new.CLIENT_ID,
      :new.CLIENT_SUBJECT_CD,
      :new.CLIENT_COMMENT
    );   
  END;
/

