CREATE OR REPLACE TRIGGER MFC_ZP_FND_V_IOUT
INSTEAD OF UPDATE ON MFC_ZP_FND_V
FOR EACH ROW 
  BEGIN  
    UPDATE MFC_ZP_FND
       SET PROOF_COMMENT = :new.PROOF_COMMENT,
           PROOF_RESULT_FG = :new.PROOF_RESULT_FG, 
           ITIL_TICKET_IF_FAILED = :new.ITIL_TICKET_IF_FAILED
     WHERE FND_ID = :old.FND_ID;   
  END;
/

