-- USER SQL
CREATE USER own_reporting IDENTIFIED BY "own_reporting"  
DEFAULT TABLESPACE "REPORT_DATA01"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER own_reporting QUOTA UNLIMITED ON REPORT_DATA01;

-- ROLES
GRANT "CONNECT" TO own_reporting ;
GRANT "ROL_OWNER" TO own_reporting ;
ALTER USER own_reporting DEFAULT ROLE "CONNECT","ROL_OWNER";

-- SYSTEM PRIVILEGES
GRANT DROP PUBLIC SYNONYM TO own_reporting ;

