-- USER SQL
CREATE USER own_recon IDENTIFIED BY "own_recon"  
DEFAULT TABLESPACE "MF_APEX_DATA01"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER own_recon QUOTA UNLIMITED ON MF_APEX_DATA01;

-- ROLES
GRANT "CONNECT" TO own_recon ;
GRANT "APEX_ADMINISTRATOR_ROLE" TO own_recon ;
ALTER USER own_recon DEFAULT ROLE "CONNECT","APEX_ADMINISTRATOR_ROLE";

-- SYSTEM PRIVILEGES
GRANT CREATE JOB TO own_recon ;
GRANT CREATE ROLE TO own_recon ;
GRANT CREATE TRIGGER TO own_recon ;
GRANT ALTER SESSION TO own_recon ;
GRANT CREATE MATERIALIZED VIEW TO own_recon ;
GRANT CREATE DIMENSION TO own_recon ;
GRANT CREATE OPERATOR TO own_recon ;
GRANT CREATE INDEXTYPE TO own_recon ;
GRANT CREATE VIEW TO own_recon ;
GRANT CREATE SESSION TO own_recon ;
GRANT CREATE TABLE TO own_recon ;
GRANT CREATE TYPE TO own_recon ;
GRANT CREATE PUBLIC SYNONYM TO own_recon ;
GRANT CREATE SYNONYM TO own_recon ;
GRANT CREATE SEQUENCE TO own_recon ;
GRANT CREATE DATABASE LINK TO own_recon ;
GRANT DROP PUBLIC SYNONYM TO own_recon ;
GRANT UNLIMITED TABLESPACE TO own_recon ;
GRANT CREATE CLUSTER TO own_recon ;
GRANT CREATE PROCEDURE TO own_recon ;

